apiVersion: v1
kind: Secret
metadata:
  name: mongo-order-credentials
type: Opaque
stringData:
  username: mongoorderuser
  password: 006bdebadf4742218e47fdcf97fc991f
  connectionString: mongodb://mongoorderuser:006bdebadf4742218e47fdcf97fc991f@mongo-order:27017