<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7535de99-6681-44ee-8fe5-88145a47769d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Order.Application\Restaurant.Order.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Data\Restaurant.Order.Data.csproj" />
    <ProjectReference Include="..\Restaurant.Order.ExternalServices\Restaurant.Order.ExternalServices.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Facade\Restaurant.Order.Facade.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Model\Restaurant.Order.Model.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Presenter\Restaurant.Order.Presenter.csproj" />
  </ItemGroup>

</Project>
