<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Order.Application\Restaurant.Order.Application.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Data\Restaurant.Order.Data.csproj" />
    <ProjectReference Include="..\Restaurant.Order.Model\Restaurant.Order.Model.csproj" />
  </ItemGroup>

</Project>
